name: log_analytics

profile: log_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  log_analytics:
    +schema: raw

models:
  log_analytics:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +schema: stg
      +materialized: view
    intermediate:
      +schema: int
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
data_tests: 
  +database: log_analytics
  +schema: testing