name: Local dbt Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    env:
      PROJECT_ROOT: /Users/tuannn/Documents/dbt/log_analytics

    steps:
      
      - name: Run dbt
        working-directory: ${{ env.PROJECT_ROOT }}/dbt
        run: |
          source .venv/bin/activate
          dbt deps
          dbt build