name: Local dbt Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    env:
      PROJECT_ROOT: /Users/tuannn/projects/log_analytics
      DBT_DIR: /Users/tuannn/projects/log_analytics/dbt

    steps:

      - name: Run dbt
        working-directory: ${{ env.DBT_DIR }}
        run: |
          source .venv/bin/activate
          dbt deps
          dbt build