name: dbt Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Activate venv and run dbt
        run: |
          source dbt/.venv/bin/activate
          dbt --version
          dbt deps
          dbt build